In [1]:
import numpy as np
import pandas as pd


In [ ]:
test_set=['CCO','CC(=O)O','ClCCBr','C1ccncc1','OS(=O)(=O)O']
def heavy_atoms(smiles):
  counts={}
  i=0
  length=len(smiles)
  while i<len(smiles):
    if smiles[i]=='C' and i!=length-1:
      if smiles[i+1]=='l':
        counts['Cl']=counts.get('cl',0)+1
        i+=2
      counts['C']=counts.get('C',0)+1
      i+=1
      continue
      if smiles[i]=='B':
        counts[Br]=counts.get('Br',0)+1
        i+=2
      continue
      if smiles[i] in []:
        i+=1
        continue
      if smiles[i]=='C':
        counts['C']=counts.get('C',0)+1
        i+=1
        continue
      if smiles[i]=='O':
        counts['O']=counts.get('O',0)+1
        i+=1
        continue


for smiles in test_set:
  print(heavy_atoms(smiles))


In [5]:
eps=np.array([[1.0,0.5],
              [0.2,1.0]])
A=np.array([1.2,0.8])
det_eps=np.linalg.det(eps)
if det_eps==0:
  print("matrix  invalid")


else:
  c=np.linalg.solve(eps,A)
  print("matrix ",c)
  res=eps@c
  print("product of eps@c:",res)
  if np.array_equal(res,A):
    print("verified")
#


matrix  [0.88888889 0.62222222]
product of eps@c: [1.2 0.8]
verified


In [12]:
A6=np.zeros((6,6))
A6[0][1]=A6[0][5]=A6[1][0]=A6[1][2]=A6[2][1]=A6[2][3]=A6[3][2]=A6[3][4]=A6[4][3]=A6[4][5]=A6[5][0]=A6[5][4]=1
eigen_values=np.linalg.eigvalsh(A6)
print(eigen_values)
vector=[]
for vec in vector:
  if vec<0:
    t='6alpha'+str(round(vec))+'beta'
  else :
    t='6alpha'+str(round(vec))+'beta'
  vector.append(t)
print(vector)

de_energy=['alpha-2 beta','alpha-1 beta','alpha-1 beta','alpha-2 beta']
print(de_energy)






[-2. -1. -1.  1.  1.  2.]
[]
['alpha-2 beta', 'alpha-1 beta', 'alpha-1 beta', 'alpha-2 beta']


In [19]:
def readout(h_agg):
  return np.sum(h_agg,axis=1)
A_n=np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]],float)
A_iso=np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]],float)
h=np.ones(4)
A=A_n+A_iso
d_n=np.sum(A,axis=1)
agg=A@h
print(A_n)
mean_n=agg/d_n
print(mean_n)
sum=np.sum(A_iso,axis=1)
agg_iso=A@h
print(agg_iso)
mean_i=agg_iso/d_n
print(mean_i)
ans1=readout(A_n)
ans2=readout(A_iso)
print(ans1)
print(ans2)

[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
[1. 1. 1. 1.]
[4. 3. 3. 2.]
[1. 1. 1. 1.]
[1. 2. 2. 1.]
[3. 1. 1. 1.]


In [20]:
T=np.array([300.0,320.,340.,360.,380.])
K=np.array([1.71e-3,6.03e-3,1.83e-2,4.92e-2,1.19e-1])
R=8.314

