In [25]:
test_set=["CCO", "CC(=O)O", "C1CCBr", "c1ccncc1" "OS(=O)(=O)O"]
def heavy_atoms(smiles):
  count={}
  for s in smiles:
    heavy_a_count=0
  i=0
  while i<len(smiles):
    char= s[i]
    if char=='C' and (i+1)<len(s) and s[i+1]=='1':
      heavy_a_count+=1
      i+=2
    elif char=='B' and (i+1)<len(s) and s[i+1]=='r':
        heavy_a_count+=1
        i+=2
    elif char in ['C','c','N','O','S','F','P','I','B']:
        heavy_a_count+=1
        i+=1
    else:
        i+=1
    count[s]=heavy_a_count
    pass
  return count
for idx in test_set:
  print(idx, heavy_atoms(idx))

IndexError: string index out of range

In [6]:

eps=np.array([[1.0,0.55],[0.2,1.0]])
A=np.array([1.2,0.8])

det_eps = np.linalg.det(eps)
print(det_eps)

conc = np.solve.linalg(eps,A)
print(conc)

prod=no.prod(conc)
print(prod)

0.89


AttributeError: module 'numpy' has no attribute 'salve'

In [21]:
A6 = np.zeros((6,6))
for i in range(0,6):
  if i+1<6:
    A6[i][i+1]=1
    A6[i+1][i]=1

eigen_values, eigen_vectors = np.linalg.eig(A6)
print(eigen_values)
print(eigen_vectors)


print(A6)



[-1.80193774 -1.2469796  -0.44504187  1.80193774  0.44504187  1.2469796 ]
[[-0.23192061 -0.41790651 -0.52112089 -0.23192061  0.52112089 -0.41790651]
 [ 0.41790651  0.52112089  0.23192061 -0.41790651  0.23192061 -0.52112089]
 [-0.52112089 -0.23192061  0.41790651 -0.52112089 -0.41790651 -0.23192061]
 [ 0.52112089 -0.23192061 -0.41790651 -0.52112089 -0.41790651  0.23192061]
 [-0.41790651  0.52112089 -0.23192061 -0.41790651  0.23192061  0.52112089]
 [ 0.23192061 -0.41790651  0.52112089 -0.23192061  0.52112089  0.41790651]]
[[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]


In [ ]:
A_nbutane = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]]),float)
A_isobutane = np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]]),float)

