ques 1

In [51]:
import numpy as np


In [52]:
test_set = ["CCO" , "CC(=O)O" , "ClCCBr" , "c1ccncc1" , "OS(=O)(=O)O"]


In [53]:
def heavy_atoms(smiles_list):
  counts = {}
  for s in smiles_list:
    heavy_atom_count = 0
    idx = 0
    while idx < len(s):
      char = s[idx]
      if char == 'C' and (idx + 1) < len(s) and s[idx+1] == 'l':
        heavy_atom_count += 1
        idx += 2
      elif char == 'B' and idx + 1 < len(s) and s[idx+1] =='r':
        heavy_atom_count += 1
        idx += 2
      elif char in ['C','c','O','N', 'S','F','P','I', 'B']:
        heavy_atom_count += 1
        idx += 1
      else:
        idx += 1
    counts[s] = heavy_atom_count
  return counts

In [68]:
for i in test_set:
  print(i ,"Toatal Heavy atoms = ", heavy_atoms([i]))

CCO Toatal Heavy atoms =  {'CCO': 3}
CC(=O)O Toatal Heavy atoms =  {'CC(=O)O': 4}
ClCCBr Toatal Heavy atoms =  {'ClCCBr': 4}
c1ccncc1 Toatal Heavy atoms =  {'c1ccncc1': 5}
OS(=O)(=O)O Toatal Heavy atoms =  {'OS(=O)(=O)O': 5}


Ques 2  

In [55]:
eps = np.array([[1.0,0.5 ] ,[0.2,1.0 ]])
A = np.array([1.2 , 0.8 ])

det_eps = np.linalg.det(eps)
print(det_eps)

conc = np.linalg.solve(eps,A)
print(conc)

prod = np.prod(conc)
print(prod)


0.9
[0.88888889 0.62222222]
0.5530864197530864


Ques 3

In [72]:
A6 = np.zeros((6,6))
for i in range(0,6):
  if i+1 < 6 :
    A6[i][i+1] = 1
    A6[i+1][i] = 1
print(A6)


eigenvalues  = np.linalg.eigvalsh(A6)
print("Eigenvalues :", eigenvalues)


eigenvalues_descending = np.sort(eigenvalues)[::-1]
print("Eigenvalues descending:", eigenvalues_descending)

delocalisation_energy = eigenvalues[0] - eigenvalues[1]
print("delocalisation_energy:", delocalisation_energy)

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]
Eigenvalues : [-1.80193774 -1.2469796  -0.44504187  0.44504187  1.2469796   1.80193774]
Eigenvalues descending: [ 1.80193774  1.2469796   0.44504187 -0.44504187 -1.2469796  -1.80193774]
delocalisation_energy: -0.5549581320873711


Ques 5

In [57]:
T = np.array([300.,320.,340.,360.,380.])
k = np.array([1.71e-3 , 6.03e-3 , 1.83e-2 , 4.92e-2 , 1.19e-1])
R = 8.314
lnk = np.log(k)
print(lnk)

[-6.37126191 -5.11100827 -4.00085422 -3.01186166 -2.12863179]


In [58]:
tinv =1/T


In [59]:
slope , intercept = np.polyfit(tinv,lnk,1)
print( "slope = " ,slope)
print("intercept = " ,intercept)
Ea = -slope*R

A = np.exp(intercept)

Ea_Kj = Ea/1000
print("Ea = " ,Ea_Kj)
lnk_pred = slope*tinv + intercept

k_pred = np.exp(lnk_pred)
resi = k_pred - k

largest_abs_resi = np.max(np.abs(resi))
print("largest absolute residual in lnk = " , largest_abs_resi)

slope =  -6045.72231497297
intercept =  13.781335399408283
Ea =  50.26413532668528
largest absolute residual in lnk =  2.341570507034818e-05


QUES 4

In [67]:
A_nbutane  = np.array([[0,1,0,0] ,[1,0,1,0] , [0,1,0,1] , [0,0,1,0]] , float)
A_isobutane = np.array([[0,1,1,1] ,[1,0,0,0] , [1,0,0,0] , [1,0,0,0]] , float)
h = np.ones(4)
sum = np.sum

sum_nbutane = A_nbutane @ h
sum_isobutane = A_isobutane @ h

print(sum_nbutane)
print(sum_isobutane)

mean_nbutane = sum_nbutane/4
mean_isobutane = sum_isobutane/4

print(mean_nbutane)
print(mean_isobutane)

readout_sum_nbutane = sum_nbutane**2
readout_sum_isobutane = sum_isobutane**2

print(readout_sum_nbutane)
print(readout_sum_isobutane)
print("squared_sum_readout",readout_sum_nbutane + readout_sum_isobutane - (mean_nbutane + mean_isobutane)**2)



[1. 2. 2. 1.]
[3. 1. 1. 1.]
[0.25 0.5  0.5  0.25]
[0.75 0.25 0.25 0.25]
[1. 4. 4. 1.]
[9. 1. 1. 1.]
squared_sum_readout [9.     4.4375 4.4375 1.75  ]
