In [7]:
#Q1 a.
test_set = ["CCO", "CC(=O)O", "ClCCBr" , "c1ccncc1", "OS(=O)(=O)O"]
def heavy_atoms(smiles):
  counts ={}
  i=0
  while i<len(smiles):
      if(smiles[i]=='C' and smiles[i+1]=='l'):
        counts['Cl']=counts.get('Cl',0)+1
        i+=2
      elif(smiles[i]=='B' and smiles[i+1]=='r'):
        counts['Br']=counts.get('Br',0)+1
        i+=2
      elif(smiles[i]=='C'):
        counts['C']=counts.get('C',0)+1
        i+=1
      elif(smiles[i]=='O'):
        counts['O']=counts.get('O',0)+1
        i+=1
      elif(smiles[i]=='c'):
        counts['C']=counts.get('C',0)+1
        i+=1
      elif(smiles[i]=='n'):
        counts['N']=counts.get('N',0)+1
        i+=1
      elif(smiles[i]=='N'):
        counts['N']=counts.get('N',0)+1
        i+=1
      elif(smiles[i]=='S'):
        counts['S']=counts.get('S',0)+1
        i+=1
      else:
        i+=1

  return counts

for smile in test_set:
  print(heavy_atoms(smile))



{'C': 2, 'O': 1}
{'C': 2, 'O': 2}
{'Cl': 1, 'C': 2, 'Br': 1}
{'C': 5, 'N': 1}
{'O': 4, 'S': 1}


1 b . it is ambiguous because Sc can be read as S-Sulphur and c-aromatic carbon . Hence in smile we solve it by representing [Sc]

In [19]:
#Q2 a.
import numpy as np
eps = np.array([[1.0,0.5],[0.2,1.0]])
A= np.array([1.2,0.8])

determi = np.linalg.det(eps)
print(determi)

c= np.linalg.solve(eps,A)
print(c)

lhs= eps@c
print(lhs)

if lhs.all()==A.all():
  print("verified")
else:
  print("False")




0.9
[0.88888889 0.62222222]
[1.2 0.8]
verified


Q2 b. Calculating inverse then solving takes more computation time than solve

In [53]:
from sys import deactivate_stack_trampoline
#Q3 a
import numpy as np

A6= np.zeros((6,6))
for i in range (len(A6)):
  A6[i][(i+1)%6] = 1
  A6[(i+1)%6][i] =1

print(A6)

eigenvalue = np.linalg.eigvalsh(A6)
eigenvalue.sort()
soted= eigenvalue[::-1]

print(soted)
Epi= 2*eigenvalue[0] + 2*eigenvalue[1] + 2*eigenvalue[2]
delocalEnergy = Epi-6
print("Epi:", Epi)
print("delocal", delocalEnergy)






[[0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]
[ 2.  1.  1. -1. -1. -2.]
Epi: -8.0
delocal -14.0


In huckel theory beta is negaqtive quantity therefore a declaration of beta negative gives overall negaive energy means the molecule is stablised

In [42]:
#q4 a
A_butane = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]])
A_isobutane= np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]])
h=np.ones(4)
sum_agg1 = A_butane@h
sum_agg2= A_isobutane@h
print(sum_agg1)
print(sum_agg2)
vod1=[]*(len(A_butane))
vod2=[]*(len(A_butane))
for i in range (len(A_butane)):
  vod1.append(sum_agg1[i])
  vod2.append(sum_agg2[i])
print(vod1)
print(vod2)

mean_agg1= sum_agg1/vod1
mean_agg2= sum_agg2/vod2
print(mean_agg1)
print(mean_agg2)


[1. 2. 2. 1.]
[3. 1. 1. 1.]
[np.float64(1.0), np.float64(2.0), np.float64(2.0), np.float64(1.0)]
[np.float64(3.0), np.float64(1.0), np.float64(1.0), np.float64(1.0)]
[1. 1. 1. 1.]
[1. 1. 1. 1.]


4 b. Degree of carbon means number of non-hydrogen groups attached to a carbon atom

In [49]:
#q5 a
T= np.array([300.,320.,340.,360.,380.])
k= np.array([1.71e-3,6.03e-3,1.83e-2,4.92e-2,1.19e-1])
R=8.314

Tinv= 1/T
print(Tinv)

lnk = np.log(k)

slope, intercept = np.polyfit(lnk,Tinv,1)
Ea= slope*R
A= np.exp(intercept)
print(Ea)
print(A)






[0.00333333 0.003125   0.00294118 0.00277778 0.00263158]
-0.0013751870862907186
1.0022821185620194


5b. intercept carries A and slope carries Ea