## Ques 1





In [1]:
import numpy as np

In [2]:
test_set = ["CCO", "CC(=O)O", "ClCCBr", "c1ccncc1", "OS(=O)(=O)O"]

In [24]:
def heavy_atoms(smiles):
  counts = {}
  i = 0
  while i< len(smiles):
    if i+1<len(smiles) and smiles[i+1].isupper():
      counts[smiles[i:i+2]] = counts.get(smiles[i:i+2], 0) + 1
      i += 2
    elif smiles[i].isupper():
      counts[smiles[i]] = counts.get(smiles[i], 0) + 1
      i += 1
    else:
      i += 1

  return counts

for s in test_set:
    print(s, heavy_atoms(s))

CCO {'CC': 1, 'O': 1}
CC(=O)O {'CC': 1, '=O': 1, ')O': 1}
ClCCBr {'C': 1, 'lC': 1, 'CB': 1}
c1ccncc1 {}
OS(=O)(=O)O {'OS': 1, '=O': 2, ')O': 1}


- Sc is ambiguous in SMILES because SMILES considers S and c as sulphur and aromatic carbon, and not as scandium. So, we need to use [Sc] to denote scandium.

## ques 2

In [3]:
import numpy as np

eps = np.array([[1.0, 0.5],
                [0.2, 1.0]])
A = np.array([1.2, 0.8])

det_eps = np.linalg.det(eps)
print(det_eps)

conc = np.linalg.solve(eps, A)
print(conc)

prod = np.prod(conc)
print(prod)

0.9
[0.88888889 0.62222222]
0.5530864197530864


## ques 3

In [11]:
import numpy as np

A6 = np.zeros((6, 6))

for i in range(6):
  if i+1<6:
    A6[i, (i+1)%6] = 1
    A6[(i+1)%6, i] = 1

eigens = np.linalg.eigvals(A6)
eigens = np.sort(eigens)[::-1]
print(eigens)

e_pi = 2*np.pi/6
print(e_pi)
print(A6)



[ 1.80193774  1.2469796   0.44504187 -0.44504187 -1.2469796  -1.80193774]
1.0471975511965976
[[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]


## ques 4

In [28]:
import numpy as np
A_nbutane = np.array([[0,1,0,0], [1,0,1,0], [0,1,0,1], [0,0,1,0]], float)
A_isobutane = np.array([[0,1,1,1], [1,0,0,0], [1,0,0,0],[1,0,0,0]], float)
h = np.ones(4)
# sum and mean aggregates, then the squared-sum readout for each

sum_nbutane = A_nbutane @ h
sum_isobutane = A_isobutane @ h
print(sum_nbutane)
print(sum_isobutane)
deg_nbutane = np.sum(A_nbutane, axis=0)
deg_isobutane = np.sum(A_isobutane, axis=0)
print(deg_nbutane)
print(deg_isobutane)
d_nbutane = deg_nbutane @ h
d_isobutane = deg_isobutane @ h
print(d_nbutane)
print(d_isobutane)
mean_nbutane = sum_nbutane/d_nbutane
mean_isobutane = sum_isobutane/d_isobutane
print(mean_nbutane)
print(mean_isobutane)
readout_sum_nbutane = sum_nbutane**2
readout_sum_isobutane = sum_isobutane**2
print(readout_sum_nbutane)
print(readout_sum_isobutane)

print("sum aggregates of nbutane", readout_sum_nbutane - mean_nbutane**2, "   of isobutane",readout_sum_isobutane - mean_isobutane**2)
print("mean aggregates of nbutane", (readout_sum_nbutane - mean_nbutane**2)/d_nbutane, "    of isobutane",(readout_sum_isobutane - mean_isobutane**2)/d_isobutane)
print("readouts for nbutane", A_nbutane @ h)
print("readouts for isobutane", A_isobutane @ h)

[1. 2. 2. 1.]
[3. 1. 1. 1.]
[1. 2. 2. 1.]
[3. 1. 1. 1.]
6.0
6.0
[0.16666667 0.33333333 0.33333333 0.16666667]
[0.5        0.16666667 0.16666667 0.16666667]
[1. 4. 4. 1.]
[9. 1. 1. 1.]
sum aggregates of nbutane [0.97222222 3.88888889 3.88888889 0.97222222]    of isobutane [8.75       0.97222222 0.97222222 0.97222222]
mean aggregates of nbutane [0.16203704 0.64814815 0.64814815 0.16203704]     of isobutane [1.45833333 0.16203704 0.16203704 0.16203704]
readouts for nbutane [1. 2. 2. 1.]
readouts for isobutane [3. 1. 1. 1.]


- the sum aggregator separates the isomers and degree of carbon states the no. of atoms the carbon is connected to.

## ques 5

In [19]:
import numpy as np
T = np.array([300., 320., 340., 360., 380.])
k= np.array([1.71e-3, 6.03e-3, 1.83e-2, 4.92e-2, 1.19e-1])
R = 8.314
log_k = np.log(k)
T_inv = 1.0/T
print(log_k)
print(T_inv)

Ea = -R*np.sum(log_k*T_inv)
print(Ea)
A_factor = np.sum(T_inv*log_k)
print(A_factor)

print("slope", -Ea/R)
print("intercept", A_factor)
print("largest absolute residual in ln k", np.max(np.abs(log_k)))

[-6.37126191 -5.11100827 -4.00085422 -3.01186166 -2.12863179]
[0.00333333 0.003125   0.00294118 0.00277778 0.00263158]
0.5233214359554933
-0.06294460379546467
slope -0.06294460379546467
intercept -0.06294460379546467
largest absolute residual in ln k 6.371261908467568


- the slope carries -Ea/R and the intercept carries lnA