In [30]:
#Q1
import numpy as np
test_set=["CCO",'CC(=O)O','ClCCBr','c1ccncc1',"OS(=O)(=O)O"]
def heavy_atoms(smiles_string):
  counts = {}
  i=0
  while i < len(smiles_string):
    if i + 1 < len(smiles_string) and smiles_string[i] == "C" and smiles_string[i+1] == 'l':
      counts["Cl"]=counts.get("Cl",0)+1
      i+=2
    elif i + 1 < len(smiles_string) and smiles_string[i] == "B" and smiles_string[i+1] == 'r':
      counts["Br"]=counts.get("Br",0)+1
      i+=2
    elif smiles_string[i] == "O":
      counts["O"]=counts.get("O",0)+1
      i+=1
    elif smiles_string[i] == "C" or smiles_string[i] == "c":
      counts["C"]=counts.get("C",0)+1
      i+=1
    elif smiles_string[i] == 'n' :
      counts["N"]=counts.get("N",0)+1 # Assuming 'n' for Nitrogen
      i+=1
    elif smiles_string[i] == 'S' :
      counts["S"]=counts.get("S",0)+1
      i+=1
    else:
      i+=1
  return counts

for smiles in test_set:
  print(f"Heavy atoms in '{smiles}': {heavy_atoms(smiles)}")

Heavy atoms in 'CCO': {'C': 2, 'O': 1}
Heavy atoms in 'CC(=O)O': {'C': 2, 'O': 2}
Heavy atoms in 'ClCCBr': {'Cl': 1, 'C': 2, 'Br': 1}
Heavy atoms in 'c1ccncc1': {'C': 5, 'N': 1}
Heavy atoms in 'OS(=O)(=O)O': {'O': 4, 'S': 1}


because sc can be interpreted as S sulphur and C carbon which we can write without brackets, therefore sc should be written inside brackets

In [31]:
#Q2
import numpy as np
eps = np.array([[1.0,0.5],
               [0.2,1.0]])
A = np.array([1.2,0.8])
det1=np.linalg.det(eps)
print(det1)
c= np.linalg.solve(eps,A)
print(c)
prod=np.dot(eps,c)
print(prod)
if np.array_equal(prod,A):
  print("verified")
else:
  print("error")

0.9
[0.88888889 0.62222222]
[1.2 0.8]
verified


inverse takes more computation time.

In [32]:
#Q3
import numpy as np
A6=np.zeros((6,6))
for i in range(len(A6)-1):
  A6[0][5]=1%6
  A6[5][0]=1%6
  A6[i][i+1]=1%6
  A6[i+1][i]=1%6
print(A6)
eign_value=np.linalg.eigvalsh(A6)
eign_value.sort()
eign=eign_value[::-1]
print(eign)
Epi=2*eign_value[0]+2*eign_value[1]+2*eign_value[2]
delocalEnergy =Epi-6
print("epi=", Epi)
print("delocalisation energy=" , delocalEnergy)

[[0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]
[ 2.  1.  1. -1. -1. -2.]
epi= -8.0
delocalisation energy= -14.0


benzene is aromatic because in HMO theory , if beta is negative it means it has low energy and there is destabilisation.

In [33]:
#Q4
import numpy as np
A_nbutane=np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]],float)
A_isobutane=np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]],float)
h=np.ones(4)
sum_isobutane=A_isobutane@h
sum_butane=A_nbutane@h
print("sum-isobutane", sum_isobutane)
print("sum-butane", sum_butane)
d1=np.linalg.norm(sum_isobutane)
d2=np.linalg.norm(sum_butane)
agg_isobutane=(A_isobutane@h)/d1
agg_butane=(A_nbutane@h)/d2
print("agg-isobutane", agg_isobutane)
print("agg-butane" , agg_butane)

sum-isobutane [3. 1. 1. 1.]
sum-butane [1. 2. 2. 1.]
agg-isobutane [0.8660254  0.28867513 0.28867513 0.28867513]
agg-butane [0.31622777 0.63245553 0.63245553 0.31622777]


degree of carbon means how many other carbon atom it is directly bonded with chemically and squared-sum readout aggregator separates the isomers

In [34]:
#Q5
import numpy as np
T=np.array([300.,320.,340.,360.,380.,])
k=np.array([1.71e-3,6.03e-3,1.83e-2,4.92e-2,1.19e-1])
R=3.14
lnk=np.log(k)
inverseT=np.reciprocal(T)
am,bn=np.polyfit(lnk,inverseT,1)
print('Slope',am)
print('Intercept',bn)
Ea=(-R*am)/1000
A=np.exp(bn)
print('Ea',Ea,"kJ per mole")
print("A",A)
print("The slope carries activation energy and intercept carries A")

Slope -0.00016540619272200128
Intercept 0.002279518484492598
Ea 5.19375445147084e-07 kJ per mole
A 1.0022821185620194
The slope carries activation energy and intercept carries A


The slope carries activation energy and intercept carries A