In [1]:
import numpy as np


ModuleNotFoundError: No module named 'Counter'

In [ ]:
from typing import Counter
def heavy_atoms(smiles):
  counts={}
  i=0
  for i in range(0,len(smiles)):
    dicti ={}
    dicti["C"]=0
    dicti["O"]=0
    dicti["Cl"]=0
    dicti["Br"]=0
    dicti["S"]=0
    dicti["N"]=0
    curr = smiles[i]
    for i in range(0,len(curr)):
      if curr[i]=="C":
        dicti["C"]=dicti["C"]+1
      elif curr[i]=="S":
        dicti["S"]=dicti["S"]+1
     elif curr[i]=="O":
        dicti["O"]=dicti["O"]+1
      elif curr[i]=="N":
        dicti["N"]=dicti["N"]+1







In [ ]:
Counter()

In [ ]:
test_set =["CC0","CC(=O)O","ClCCBr","c1ccncc1","OS(=O)(=O)O"]

AttributeError: module 'numpy' has no attribute 'Counter'

In [40]:
#2
eps = np.array([[1.0,0.5],[0.2,1.0]])
A = np.array([1.2,0.8])

In [41]:
A

array([1.2, 0.8])

In [42]:
eps

array([[1. , 0.5],
       [0.2, 1. ]])

In [43]:
#chweck invers
ans=np.linalg.det(eps)
ans

np.float64(0.9)

In [44]:
#det not 0 so invertible
eps_inv = np.linalg.inv(eps)
eps_inv

array([[ 1.11111111, -0.55555556],
       [-0.22222222,  1.11111111]])

In [45]:
det_eps = np.linalg.det(eps)
det_eps

np.float64(0.9)

In [46]:
#a=eps*c*l--->so c = a*eps-1
c=A@eps_inv
c

array([1.15555556, 0.22222222])

In [47]:
eps@c

array([1.26666667, 0.45333333])

In [48]:
print(eps)

[[1.  0.5]
 [0.2 1. ]]


In [ ]:
#solvng is preferred than np.linalg.inv(eps) because at the end it is not verified,solving could give good result

In [49]:
#4.
A_nbutane = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]],float)
A_isobutane = np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]],float)
h = np.ones(4)
print(A_nbutane)
print(A_isobutane)
print(h)

[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
[[0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[1. 1. 1. 1.]


In [50]:
sum_agg_nbutane = A_nbutane@h
sum_agg_nbutane

array([1., 2., 2., 1.])

In [51]:
sum_agg_isobutane = A_isobutane@h
sum_agg_isobutane

array([3., 1., 1., 1.])

In [52]:
d_but = np.sum(A_nbutane,axis =1)
d_but

array([1., 2., 2., 1.])

In [53]:
mean_agg_nbutane = (A_nbutane@h)/d_but
mean_agg_nbutane

array([1., 1., 1., 1.])

In [54]:
d_iso= np.sum(A_isobutane,axis =1)
d_iso

array([3., 1., 1., 1.])

In [55]:
mean_agg_isobutane = (A_isobutane@h)/d_iso
mean_agg_isobutane

array([1., 1., 1., 1.])

In [57]:
#grap level readout
sq_sum_agg_nbut = np.array(sum_agg_nbutane**2)
sq_sum_agg_nbut


array([1., 4., 4., 1.])

In [59]:
np.sum(sq_sum_agg_nbut)

np.float64(10.0)

In [58]:
sq_sum_agg_iso = np.array(sum_agg_isobutane**2)
sq_sum_agg_iso


array([9., 1., 1., 1.])

In [60]:
np.sum(sq_sum_agg_iso)

np.float64(12.0)

In [65]:
sq_mean_agg_iso = np.array(mean_agg_isobutane**2)
sq_mean_agg_iso


array([1., 1., 1., 1.])

In [67]:
np.sum(sq_sum_agg_iso+sq_mean_agg_iso)

np.float64(16.0)

In [61]:
sq_mean_agg_nbut = np.array(mean_agg_nbutane**2)
sq_mean_agg_nbut

array([1., 1., 1., 1.])

In [83]:
sq_mean_agg_isobut = np.array(mean_agg_isobutane**2)
sq_mean_agg_isobut

array([1., 1., 1., 1.])

In [84]:
np.sum(sq_sum_agg_nbut+sq_mean_agg_nbut)

np.float64(14.0)

In [85]:
sq_sum_agg_nbut+sq_mean_agg_nbut

array([2., 5., 5., 2.])

In [62]:
np.sum(sq_mean_agg_nbut)

np.float64(4.0)

In [63]:
sq_sum_agg_nbut+sq_mean_agg_nbut

array([2., 5., 5., 2.])

In [64]:
np.sum(sq_sum_agg_nbut+sq_mean_agg_nbut)

np.float64(14.0)

In [68]:
#5.
import numpy as np
T=np.array([300.,320.,340.,360.,380.])
k=np.array([1.71e-3,6.03e-3,1.83e-2,4.92e-2,1.19e-1])
R=8.314

In [70]:
lnk = np.log2(k)
lnk

array([-9.19178796, -7.37362628, -5.77201254, -4.34519787, -3.07096652])

In [72]:
invt = 1/T
invt

array([0.00333333, 0.003125  , 0.00294118, 0.00277778, 0.00263158])

In [76]:
coeff = np.polyfit(invt,lnk,1)

In [77]:
coeff

array([-8722.1336024 ,    19.88226424])

In [78]:
E_a = -coeff[0]*R

In [80]:
E_a/1000 # in kj

np.float64(72.51581877038055)

In [82]:
A= np.exp(coeff[1])
A

np.float64(431278338.90505135)

In [ ]:
#the slope is carried by first coeff ,and ie -ea/r ;the second output of coeff is intercept =lna