In [33]:
# Q1 Counting heavy atoms with SMILES

test_set = ["CCO", "CC(=O)O", "ClCCBr", "c1ccncc1", "OS(=O)(=O)O"]

def heavy_atoms(smiles):
  counts = dict()

  for key in ["C", "O", "N", "S", "Cl", "Br"]:
    counts[key] = 0

  s = smiles.upper()

  j = 0
  while j < len(s):
    if j + 1 < len(s):
      if s[j:j+2] == 'CL':
        counts["Cl"] += 1
        j += 2
        continue
      elif s[j:j+2] == 'BR':
        counts["Br"] += 1
        j += 2
        continue

    if s[j] == 'C':
      counts["C"] += 1
    elif s[j] == 'O':
      counts["O"] += 1
    elif s[j] == 'N':
      counts["N"] += 1
    elif s[j] == 'S':
      counts["S"] +=1

    j += 1

  return counts

for i in range(len(test_set)):
  D = heavy_atoms(test_set[i])
  for key in D:
    if(D[key] > 0):
      print(key, " : ", D[key],end=", ")
  print()

C  :  2, O  :  1, 
C  :  2, O  :  2, 
C  :  2, Cl  :  1, Br  :  1, 
C  :  5, N  :  1, 
O  :  4, S  :  1, 


Sc is ambigous because it can be interpreted both as **Sc (Scandium)** and **S (sulphur)** followed by **C (Carbon)**. It is resolved by using square bracket notations.


In [34]:
# Q2 Two component beer-lambert deconvolve

import numpy as np

eps = np.array([[1.0, 0.5],
               [0.2, 1.0]])

A = np.array([1.2, 0.8])

det = np.linalg.det(eps)
c = np.linalg.solve(eps, A)
dot = np.dot(eps, c)

print("Determinant of eps: ", det)
print("Concentration vector C: ", c)
print("Dot product eps @ C", dot)

if np.array_equal(dot, A):
  print("Equation eps @ C = A is verified")
else:
  print("Equation eps @ C = A is NOT verified")

Determinant of eps:  0.9
Concentration vector C:  [0.88888889 0.62222222]
Dot product eps @ C [1.2 0.8]
Equation eps @ C = A is verified


np.linalg.solve() is preferred over np.linalg.inv() @ A for solving linear systems because it is both more numerically stable, since it avoids inverse calculations, and generally more computationally efficient.

In [35]:
# Q3 Huckel spectrum of benzene

import numpy as np

A6 = np.zeros((6,6))

for i in range(6):
  A6[i, (i + 1) % 6] = 1
  A6[(i + 1) % 6, i] = 1

eigenvalues = np.linalg.eigvalsh(A6)
eigenvalues.sort()
eigenvalues = eigenvalues[::-1]

E_pi = 2 * eigenvalues[0] + 2 * eigenvalues[1] + 2 * eigenvalues[2]

delocal_energy_coeff = E_pi - 6

print("Adjacency Matrix (A6):\n", A6)
print("\nEigenvalues (descending):", eigenvalues)
print(f"\nE_pi: 6*alpha + {E_pi:.0f}*beta")
print(f"Delocalisation Energy: {delocal_energy_coeff:.0f}*beta")

Adjacency Matrix (A6):
 [[0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]

Eigenvalues (descending): [ 2.  1.  1. -1. -1. -2.]

E_pi: 6*alpha + 8*beta
Delocalisation Energy: 2*beta


  In Hückel theory, the resonance integral 'beta' is negative energy quantity. Therefore, a delocalization energy of '2beta' represents a negative overall energy contribution, which signifies a stabilization of the molecule. This extra stabilization, compared to a non-conjugated reference (three isolated ethylene units in this case), denotes that benzene is aromatic

In [36]:
# Q4 Sum against mean aggregation

import numpy as np

A_nbutane = np.array([[0,1,0,0],[1,0,1,0],[0,1,0,1],[0,0,1,0]], float)
A_isobutane = np.array([[0,1,1,1],[1,0,0,0],[1,0,0,0],[1,0,0,0]], float)
h = np.ones(4)

d_nbutane = np.sum(A_nbutane, axis=1)
sum_agg_nbutane = np.dot(A_nbutane, h)
mean_agg_nbutane = sum_agg_nbutane / d_nbutane

readout_nbutane = np.sum(mean_agg_nbutane**2)

print("Degrees nbutane:", d_nbutane)
print("Sum Aggregate of nbutane:", sum_agg_nbutane)
print("Mean Aggregate of nbutane:", mean_agg_nbutane)
print("Graph-level Readout of n-butane:", readout_nbutane)
print()
d_isobutane = np.sum(A_isobutane, axis=1)
sum_agg_isobutane = np.dot(A_isobutane, h)
mean_agg_isobutane = sum_agg_isobutane / d_isobutane

readout_isobutane = np.sum(mean_agg_isobutane**2)

print("Degrees d_isobutane:", d_isobutane)
print("Sum Aggregate isobutane:", sum_agg_isobutane)
print("Mean Aggregate isobutane:", mean_agg_isobutane)
print("Graph-level Readout of iso-butane:", readout_isobutane)
print()

if np.isclose(readout_nbutane, readout_isobutane):
    print("The two molecules are NOT separated based on their squared-sum readouts (readouts are approximately equal).")
else:
    print("The two molecules ARE separated based on their squared-sum readouts (readouts are different).")

Degrees nbutane: [1. 2. 2. 1.]
Sum Aggregate of nbutane: [1. 2. 2. 1.]
Mean Aggregate of nbutane: [1. 1. 1. 1.]
Graph-level Readout of n-butane: 4.0

Degrees d_isobutane: [3. 1. 1. 1.]
Sum Aggregate isobutane: [3. 1. 1. 1.]
Mean Aggregate isobutane: [1. 1. 1. 1.]
Graph-level Readout of iso-butane: 4.0

The two molecules are NOT separated based on their squared-sum readouts (readouts are approximately equal).


  The degrees aggregator separates the isomers as their degree vectors are different, and chemically, the degree of a carbon atom signifies the number of other atoms it is directly bonded to (other than hydrogen), or a ring.

In [37]:
# Q5 Arrhenius parameters by least squares

import numpy as np

T = np.array([300.,  320., 340., 360., 380.,])
k = np.array([1.71e-3, 6.03e-3, 1.83e-2, 4.92e-2, 1.19e-1])
R = 8.314

ln_k = np.log(k)
inv_T = 1 / T

slope, intercept = np.polyfit(inv_T, ln_k, 1)

Ea = -slope * R
Ea_kJ_mol = Ea / 1000
A = np.exp(intercept)

predicted_ln_k = slope * inv_T + intercept
residuals = ln_k - predicted_ln_k
largest_abs_residual = np.max(np.abs(residuals))

print(f"Slope: {slope:.4f}")
print(f"Intercept: {intercept:.4f}")
print(f"Activation Energy (Ea): {Ea_kJ_mol:.2f} kJ/mol")
print(f"Pre-exponential Factor (A): {A:.2e}")
print(f"Largest Absolute Residual in ln k: {largest_abs_residual:.4f}")


Slope: -6045.7223
Intercept: 13.7813
Activation Energy (Ea): 50.26 kJ/mol
Pre-exponential Factor (A): 9.66e+05
Largest Absolute Residual in ln k: 0.0007


In the linear fit of ln(k) vs 1/T, the slope carries -Ea/R and the intercept carries ln(A).