Ques 1

In [81]:
def heavy_atoms(smiles):
  counts={}
  i=0;
  while i<len(smiles):
    if smiles[i:i+2] == "Br" or smiles[i:i+2] == "Cl":
      temp = smiles[i:i+2]
      i += 2
    elif smiles[i] in ['C', 'c', 'O', 'o', 'S', 's', 'N', 'n']:
      temp = smiles[i].upper()
      i += 1
    else:
      i += 1
      continue
    if temp in counts:
      counts[temp] += 1
    else:
      counts[temp] = 1

  return counts

In [82]:
test_set = ["CCO", "CC(=O)O", "ClCCBr", "c1ccncc1", "OS(=O)(=O)O"]
for ch in test_set:
  print(heavy_atoms(ch))

{'C': 2, 'O': 1}
{'C': 2, 'O': 2}
{'Cl': 1, 'C': 2, 'Br': 1}
{'C': 5, 'N': 1}
{'O': 4, 'S': 1}


Sc is ambigous because it contains both the char as S and c which means Sulphur and Carbon respectively, since in the function we are checking two word element first so Sc is dentified as Sc and not S or c

Ques 2

In [83]:
import numpy as np

eps = np.array([[1.0, 0.5],
                [0.2, 1.0]])
A = np.array([1.2, 0.8])

print("Determinant of eps:", np.linalg.det(eps))
c = np.linalg.solve(eps,A)
print("C:",c)
eps_c = np.linalg.matmul(eps,c)
print("eps@c:", eps_c)
if np.array_equal(eps_c,A):
  print("VERIFIED")
else:
  print("NOT VERIFIED")

Determinant of eps: 0.9
C: [0.88888889 0.62222222]
eps@c: [1.2 0.8]
VERIFIED


Ques 3

In [84]:
import numpy as np
A = np.zeros((6,6))
for i in range(6):
  A[i][(i+1)%6]=1
  A[i][(5-i)%6]=1
print(A)
eigen = np.linalg.eigvals(A)
eigen.sort()
eigen = eigen[::-1]
print("Eigenvalues:", eigen)

[[0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]
Eigenvalues: [ 1.61803399e+00  6.18033989e-01  4.42506570e-17  0.00000000e+00
 -6.18033989e-01 -1.61803399e+00]


Ques 4

In [85]:
import numpy as np

A_nbutane = np.array([[0,1,0,0], [1,0,1,0], [0,1,0,1], [0,0,1,0]], float)
A_isobutane = np.array([[0,1,1,1], [1,0,0,0], [1,0,0,0], [1,0,0,0]], float)

h = np.ones(4)
sum_agg_nbutane = A_nbutane@h
sum_agg_isobutane = A_isobutane@h
print("sum_agg_nbutane:", sum_agg_nbutane)
print("sum_agg_isobutane:", sum_agg_isobutane)
d1 = np.linalg.norm(sum_agg_isobutane)
d2 = np.linalg.norm(sum_agg_nbutane)
print("d1:", d1)
print("d2:", d2)
mean_agg_nbutane = sum_agg_nbutane/d2
mean_agg_isobutane = sum_agg_isobutane/d1
print("mean_agg_nbutane:", mean_agg_nbutane)
print("mean_agg_isobutane:", mean_agg_isobutane)

sum_agg_nbutane: [1. 2. 2. 1.]
sum_agg_isobutane: [3. 1. 1. 1.]
d1: 3.4641016151377544
d2: 3.1622776601683795
mean_agg_nbutane: [0.31622777 0.63245553 0.63245553 0.31622777]
mean_agg_isobutane: [0.8660254  0.28867513 0.28867513 0.28867513]


The degree of freedoms seperates the 2 molecules

Ques 5

In [86]:
import numpy as np

T = np.array([300., 320., 340., 360., 380.])
k = np.array([1.71e-3, 6.03e-3, 1.83e-2, 4.92e-2, 1.19e-1])
R = 8.314

ln_k = np.log(k)
inv_T = np.reciprocal(T)

a, b = np.polyfit(ln_k, inv_T, 1)
print("Slope:", a)
print("Intercept:", b)
Ea = (-R*a)/1000
A = np.exp(b)
print("Ea:", Ea, "Kj per mol")
print("A:", A)
print(" The slope carries Activation Energy and the intercept carries A")


Slope: -0.00016540619272200128
Intercept: 0.002279518484492598
Ea: 1.3751870862907186e-06 Kj per mol
A: 1.0022821185620194
 The slope carries Activation Energy and the intercept carries A
