In [2]:
import numpy as np
import pandas as pd

In [68]:
test_set = ["CCO", "CC(=O)O", "ClCCBr","c1ccncc1","OS(=O)(=O)O"]
def heavy_atoms(smiles):
  counts = {}
  i = 0
  length = len(smiles)
  while i < length:
    if smiles[i] == 'C' and i != length-1:
      if smiles[i+1] == 'l' :
        counts['Cl'] = counts.get('Cl',0) + 1
        i+=2
      else:
        counts['C'] = counts.get['C',0] + 1
        i+=1
        continue
    if smiles[i] == 'B':
        counts[Br]= counts.get('Br',0) + 1
        i+=2
        continue
    if smiles[i] in ['-','=','#',':']:
          i+=1
          continue
    if smiles[i] == 'C':
          counts['C'] = counts.get('C',0) + 1
          i+=1
          continue
    if smiles[i] == 'O':
          counts['O'] = counts.get('O',0) + 1
          i+=1
          continue
    if smiles[i] == 'N':
          counts['N'] = counts.get('N',0) + 1
          i+=1
          continue

    counts[smiles[i]] = counts.get(smiles[i],0) + 1
    i+=1
    continue
    return counts
    for smile in test_set:
      print(heavy_atoms(smiles))



In [25]:
eps = np.array([[1.0,0.5],[0.2,1.0]])
A = np.array([1.2,0.8])
det_eps = np.linalg.det(eps)
print("det of matrix " + str(det_eps))
if det_eps == 0:
  print("matrix not invertible")
else:
    c = np. linalg.solve(eps,A)
    print ("matrix",c)
res = eps@c
print("product of eps @ c: " , res)
if np.array_equal(res,A):
  print("verified")



det of matrix 0.9
matrix [0.88888889 0.62222222]
product of eps @ c:  [1.2 0.8]
verified


In [48]:
A6 = np.zeros((6,6))

A6[0][1] = A6[0][5]=  A6[1][0] = A6[1][2] = A6[2][1] = A6[2][3] = A6[3][2] = A6[3][4] = A6[4][3] = A6[4][5] = A6[5][0] = A6[5][4] = 1

eigen_values = np.linalg.eigvalsh(A6)
print(eigen_values)

vector = []
for vec in vector:
    if vec < 0:
     t = "6alpha" + str(round(vec)) + "beta"
    else:
        t = "6alpha" + str(round(vec)) + "beta"
        vector.append(t)
print(vector)
de_energy = ["alpha-2 beta", "alpha-1 beta" , "alpha-1 beta" , "alpha-2 beta"]
print(de_energy)


[-2. -1. -1.  1.  1.  2.]
[]
['alpha-2 beta', 'alpha-1 beta', 'alpha-1 beta', 'alpha-2 beta']


In [59]:
def readout(A_agg):
    return np.sum(A_agg)

A_n = np.array([[0,1,0,0], [1,0,1,0], [0,1,0,1] , [0,0,1,0]])
A_iso = np.array([[0,1,1,1], [1,0,0,0], [1,0,0,0] , [1,0,0,0]])
h = np.ones(4)

d_n = np.sum(A,axis = 1)

agg = A_n @ h
print(A_n)
mean_n = agg/d_n
print(mean_n)
d_i = np.sum(A_iso , axis =1)

agg_iso = A_iso @ h
print(agg_iso)
mean_i = agg_iso/d_i
print(mean_i)

ans1 = readout(A_n)
ans2 = readout(A_iso)
print(ans1)
print(ans2)



[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 0]]
[0.25       0.66666667 0.66666667 0.5       ]
[3. 1. 1. 1.]
[1. 1. 1. 1.]
6
6


In [ ]:
T = np.array([300.,320.,340.,360.,380])
