##Q1

In [16]:
reactions = [
    "CC(=O).OCC>[H+].[C1-]>CC(=O)OCC.O",
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[=O][O-].O",
]

def parse_reaction(rxn):
  # split on ">", check there are three fields
  parts = rxn.split('>')
  if len(parts) != 3:
    raise ValueError("Reaction string must have exactly two '>' delimiters (reactants>agents>products)")

  reactants_str, agents_str, products_str = parts

  # split each field on "." and drop empty entries
  reactants = [s.strip() for s in reactants_str.split('.') if s.strip()]
  agents = [s.strip() for s in agents_str.split('.') if s.strip()]
  products = [s.strip() for s in products_str.split('.') if s.strip()]

  return {'reactants': reactants, 'agents': agents, 'products': products}

##Q2

In [22]:
import numpy as np

# columns: C2H6, O2, CO2, H2O      rows: C, H, O
E = np.array([[2., 0., -1., 0.],
              [6., 0., 0., -2.],
              [0., 2., -2., -1.]])

# SVD, extract the null vector, rescale, verify E @ x = 0

U, s, Vt = np.linalg.svd(E)

null_vector_unscaled = Vt[-1, :]

if null_vector_unscaled[0] < 0:
    null_vector_unscaled *= -1

print(f"Null vector (unscaled) from SVD: {null_vector_unscaled}")

verification_result = E @ null_vector_unscaled
print(f"E @ null_vector_unscaled = {verification_result}")

print(f"Is E @ null_vector_unscaled approximately zero? {np.allclose(verification_result, 0)}")

Null vector (unscaled) from SVD: [0.19518001 0.68313005 0.39036003 0.58554004]
E @ null_vector_unscaled = [-5.55111512e-17 -2.22044605e-16 -1.11022302e-16]
Is E @ null_vector_unscaled approximately zero? True


## Q3

In [24]:
import numpy as np

A = np.zeros((6,6))

# bond atom i to atom i+1 for i=0, 1, 2 (a chain, not a ring)
# This means bonds between (0,1), (1,2), (2,3) with beta (1.0 in this model)
for i in range(3):
    A[i, i+1] = A[i+1, i] = 1.0

print("Hückel matrix A for the 4-atom chain (and 2 isolated atoms):")
print(A)

eigenvalues = np.linalg.eigvalsh(A)

eigenvalues_sorted = np.sort(eigenvalues)[::-1]
print(f"\nEigenvalues (in units of β, sorted descending): {eigenvalues_sorted}")

E_pi = 2 * (eigenvalues_sorted[0] + eigenvalues_sorted[1])
print(f"E_pi (pi electron energy, in units of β): {E_pi:.3f}")

reference_energy = 4.0
delocalization_energy = E_pi - reference_energy
print(f"Delocalization energy (in units of β): {delocalization_energy:.3f}")

Hückel matrix A for the 4-atom chain (and 2 isolated atoms):
[[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Eigenvalues (in units of β, sorted descending): [ 1.61803399  0.61803399  0.          0.         -0.61803399 -1.61803399]
E_pi (pi electron energy, in units of β): 4.472
Delocalization energy (in units of β): 0.472


##Q4

In [5]:
import numpy as np
A6 = np.zeros((6,6))
for i in range(6):
  A6[i, (i + 1) % 6] = A6[(i + 1) % 6, i] =1.0

H = np.random.default_rng(1).normal(size=(6,3))    # do not change the seed



# TODO: A_tilde, the row-stochastic P, the smoothing rate mu,
#       then the largest deviation from the main row at k = 0, 1, 2, 4, 8, 16

##Q5

In [17]:
import numpy as np

X = np.array([[78.1, 2.3],
              [92.1, 1.7],
              [106.2, 2.8],
              [120.2, 2.0],
              [134.2, 3.1],
              [148.2, 2.4]])     # molar mass (g/mol), dipole moment (D)

# TODO: centered PCA, then standardised PCA, then compare