Question 1

In [32]:
reactions = [
    "CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O",
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O",
]
def parse_reaction(rxn):
    f = rxn.split(">")
    if len(f) != 3: raise ValueError("need exactly two '>'")
    return {k: [m for m in x.split(".") if m]
            for k, x in zip(["reactants","reagents","products"], f)}

for r in reactions:
    d = parse_reaction(r)
    print(r); [print(" ", k, len(v), v) for k, v in d.items()]
    print(" ")

print("Reaction 1 is esterification")
print("Empty reagent means no catalyst/solvent was recorded")

CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O
  reactants 2 ['CC(=O)O', 'OCC']
  reagents 2 ['[H+]', '[Cl-]']
  products 2 ['CC(=O)OCC', 'O']
 
C=C.[H][H]>[Pd]>CC
  reactants 2 ['C=C', '[H][H]']
  reagents 1 ['[Pd]']
  products 1 ['CC']
 
c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O
  reactants 2 ['c1ccccc1', 'O=[N+]([O-])O']
  reagents 0 []
  products 2 ['c1ccccc1[N+](=O)[O-]', 'O']
 
Reaction 1 is esterification
Empty reagent means no catalyst/solvent was recorded


Question 2

In [33]:
import numpy as np
E = np.array([
 [2.,0.,-1.,0.],
 [6.,0.,0.,-2.],
 [0.,2.,-2.,-1.]
])

S = np.linalg.svd(E, compute_uv=False)
v = np.linalg.svd(E)[2][-1]
x = v/v[0]; xw = x*2
print(S)
print((S>1e-10).sum())
print(4-(S>1e-10).sum())
print(x)
print(xw)
print(np.round(E@xw))

print()
print("Nullity 1 means the balancing is unique upto to an overall scale factor")

[6.62561256 3.00720721 1.02857332]
3
1
[1.  3.5 2.  3. ]
[2. 7. 4. 6.]
[-0. -0. -0.]

Nullity 1 means the balancing is unique upto to an overall scale factor


Question 3

In [34]:
import numpy as np
A = np.zeros((4,4))

A = np.diag([1.,1.,1.], 1); A += A.T
w = np.sort(np.linalg.eigvalsh(A))[::-1]
print(w)
print(A.sum(1))
print(2*w[0]+2*w[1])
print(2*w[0]+2*w[1]-4)
print()
print("Butadiene's 0.472β is far smaller than benzene's 2β, so butadiene is only weakly delocalised while benzene is aromatically stabilised.")

[ 1.61803399  0.61803399 -0.61803399 -1.61803399]
[1. 2. 2. 1.]
4.47213595499958
0.4721359549995796

Butadiene's 0.472β is far smaller than benzene's 2β, so butadiene is only weakly delocalised while benzene is aromatically stabilised.


Question 4

In [35]:
import numpy as np

A6 = np.zeros((6,6))
for i in range(6):
  A6[i, (i+1)%6] = A6[(i+1)%6, i] = 1.0

H = np.random.default_rng(1).normal(size=(6,3))

At = A6 + np.eye(6); P = At/At.sum(1, keepdims=True)
m = np.sort(abs(np.linalg.eigvals(P)))[::-1]
print(m, m[1])
for k in [0,1,2,4,8,16]:
    Hk = np.linalg.matrix_power(P,k)@H
    print(k, np.linalg.norm(Hk-Hk.mean(0), axis=1).max())

print()
print("Deviation decays like μᵏ, so beyond ~3–4 layers atoms become nearly indistinguishable.")

[1.00000000e+00 6.66666667e-01 6.66666667e-01 3.33333333e-01
 7.91848035e-17 3.92523115e-17] 0.6666666666666667
0 1.2413880520727198
1 0.5368253372377662
2 0.3459101833698204
4 0.15487263988972352
8 0.03066757345525804
16 0.0011967999497353888

Deviation decays like μᵏ, so beyond ~3–4 layers atoms become nearly indistinguishable.


Question 5

In [36]:
import numpy as np

X = np.array([
    [78.1, 2.3],
    [92.1, 1.7],
    [106.2, 2.8],
    [120.2, 2.0],
    [134.2, 3.1],
    [148.2, 2.4]
])
def pca(M):
    C = M.T@M/len(M); w,V = np.linalg.eigh(C)
    i = np.argsort(w)[::-1]; w,V = w[i], V[:,i]
    V *= np.sign(V[abs(V).argmax(0), [0,1]])
    print(C, w, w/w.sum(), V[:,0])


Xc = X - X.mean(0)
pca(Xc)
print()
pca(Xc/Xc.std(0))
print()

print("Molar mass has a variance ~2600× larger than dipole moment, so unstandardised PCA just recovers the mass axis, the standardised result is the one to report.")

[[5.73535556e+02 4.56277778e+00]
 [4.56277778e+00 2.18055556e-01]] [5.73571866e+02 1.81744746e-01] [9.99683236e-01 3.16764448e-04] [0.99996834 0.0079578 ]

[[1.         0.40800508]
 [0.40800508 1.        ]] [1.40800508 0.59199492] [0.70400254 0.29599746] [0.70710678 0.70710678]

Molar mass has a variance ~2600× larger than dipole moment, so unstandardised PCA just recovers the mass axis, the standardised result is the one to report.
