In [37]:
import numpy as np
import math

Q1.

In [55]:
reactions = [
    "CC(=o)O.OCC>[H+].[Cl-]>CC(=O)OCC.O" ,
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])>>c1ccccc1[N+](=O)[O-].O",
]

def split_rxns(rxn) :
  components = rxn.split(".")
  #print("Reactions components : ")
  #print(components)
  if (len(components) == 0 or (len(components) == 1 and len(components[0]) == 0)) :
    return []
  return components

def parse_reaction(rxn) :
  parsed_rxn_arr = rxn.split(">");
  if (len(parsed_rxn_arr) < 3) :
    print("Invalid Reaction")
    return
  # print(parsed_rxn_arr[0] , parsed_rxn_arr[1] , parsed_rxn_arr[2])
  reactants = split_rxns(parsed_rxn_arr[0])
  reagents = split_rxns(parsed_rxn_arr[1])
  products = split_rxns(parsed_rxn_arr[2])

  ans = {
      "reactants" : reactants ,
      "reagents" : reagents ,
      "products" : products
  }
  return ans;

def get_count_of_molecules(rxn) :
  reactants = rxn["reactants"]
  reagents = rxn["reagents"]
  products = rxn["products"]

  print("No. of Reactants : " , len(reactants))
  print("Reactants : " , reactants)
  print("No. of Reagents : " , len(reagents))
  print("Reagents : " , reagents)
  print("No. of Products : " , len(products))
  print("Products : " , products)

rxn1 = parse_reaction(reactions[0])
rxn2 = parse_reaction(reactions[1])
rxn3 = parse_reaction(reactions[2])

print("For 1st Reaction : ")
get_count_of_molecules(rxn1)

print("For 2nd Reaction : ")
get_count_of_molecules(rxn2)

print("For 3rd Reaction : ")
get_count_of_molecules(rxn3)

print("Reaction 1 is esterification")
print("Empty reagent means no catalyst/solvent was recorded")




For 1st Reaction : 
No. of Reactants :  2
Reactants :  ['CC(=o)O', 'OCC']
No. of Reagents :  2
Reagents :  ['[H+]', '[Cl-]']
No. of Products :  2
Products :  ['CC(=O)OCC', 'O']
For 2nd Reaction : 
No. of Reactants :  2
Reactants :  ['C=C', '[H][H]']
No. of Reagents :  1
Reagents :  ['[Pd]']
No. of Products :  1
Products :  ['CC']
For 3rd Reaction : 
No. of Reactants :  2
Reactants :  ['c1ccccc1', 'O=[N+]([O-])']
No. of Reagents :  0
Reagents :  []
No. of Products :  2
Products :  ['c1ccccc1[N+](=O)[O-]', 'O']
Reaction 1 is esterification
Empty reagent means no catalyst/solvent was recorded


Q2.

In [54]:
E = np.array([
    [2. , 0., -1. , 0.],  [6. , 0., 0., -2.] , [0., 2., -2., -1.]
  ])
U, s, Vh = np.linalg.svd(E)
#print(Vh)
null_vector = Vh[-1, :]


x = null_vector
print("Null vector x:", x)

scaled_null_vector = null_vector / null_vector[0]
print("Scaled to make CsH6 coefficient 1 : " , scaled_null_vector)

scaled_to_whole = scaled_null_vector * 2;
print("Scaled to smallest whole numbers : " , scaled_to_whole)

result = E @ x
print("E @ x:", result)
print("E @ x is close to zero:", np.allclose(result, 0))

print("Nullity 1 means the balancing is unique upto to  overall scale factor")

Null vector x: [0.19518001 0.68313005 0.39036003 0.58554004]
Scaled to make CsH6 coefficient 1 :  [1.  3.5 2.  3. ]
Scaled to smallest whole numbers :  [2. 7. 4. 6.]
E @ x: [-5.55111512e-17 -2.22044605e-16 -1.11022302e-16]
E @ x is close to zero: True
Nullity 1 means the balancing is unique upto to an overall scale factor


Q3

In [53]:
A = np.zeros((4 , 4))

for i in range(4) :
  if (i +1 < 4) :
    A[i][i+1] = 1
    A[i+1][i] = 1
print(A)

eigenvalues  = np.linalg.eigvalsh(A)
print("Eigenvalues :", eigenvalues)

eigenvalues_descending = np.sort(eigenvalues)[::-1]
print("Eigenvalues descending:", eigenvalues_descending)

E_pi = 2*eigenvalues_descending[0] + 2*eigenvalues_descending[1]
print("E_pi: 2 * alpha + beta *", E_pi)

delocalisation_energy = E_pi - 4
print("delocalisation_energy:", delocalisation_energy)

print("Butadiene's 0.472β is far smaller than benzene's 2β, so butadiene is only weakly delocalised while benzene is aromatically stabilised.")


[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]
Eigenvalues : [-1.61803399 -0.61803399  0.61803399  1.61803399]
Eigenvalues descending: [ 1.61803399  0.61803399 -0.61803399 -1.61803399]
E_pi: 2 * alpha + beta * 4.47213595499958
delocalisation_energy: 0.4721359549995796
Butadiene's 0.472β is far smaller than benzene's 2β, so butadiene is only weakly delocalised while benzene is aromatically stabilised.


Q4.

In [51]:
import numpy as np

A6 = np.zeros((6,6))
for i in range(6):
  A6[i, (i+1)%6] = A6[(i+1)%6, i] = 1.0

H = np.random.default_rng(1).normal(size=(6,3))

At = A6 + np.eye(6); P = At/At.sum(1, keepdims=True)
m = np.sort(abs(np.linalg.eigvals(P)))[::-1]
print(m, m[1])
for k in [0,1,2,4,8,16]:
    Hk = np.linalg.matrix_power(P,k)@H
    print(k, np.linalg.norm(Hk-Hk.mean(0), axis=1).max())

print("Deviation decays like μ^k, so beyond approx 3–4 layers atoms become almost indistinguishable.")

[1.00000000e+00 6.66666667e-01 6.66666667e-01 3.33333333e-01
 7.91848035e-17 3.92523115e-17] 0.6666666666666667
0 1.2413880520727198
1 0.5368253372377662
2 0.3459101833698204
4 0.15487263988972352
8 0.03066757345525804
16 0.0011967999497353888

Deviation decays like μᵏ, so beyond ~3–4 layers atoms become nearly indistinguishable.


Q5.

In [52]:
import numpy as np

X = np.array([
    [78.1, 2.3],
    [92.1, 1.7],
    [106.2, 2.8],
    [120.2, 2.0],
    [134.2, 3.1],
    [148.2, 2.4]
])
def pca(M):
    C = M.T@M/len(M); w,V = np.linalg.eigh(C)
    i = np.argsort(w)[::-1]; w,V = w[i], V[:,i]
    V *= np.sign(V[abs(V).argmax(0), [0,1]])
    print(C, w, w/w.sum(), V[:,0])


Xc = X - X.mean(0)
pca(Xc)
print()
pca(Xc/Xc.std(0))
print()

print("Molar mass has variance ~2600× larger than dipole moment, so unstandardised PCA just recovers the mass axis, the standardised result is the one to report.")


[[5.73535556e+02 4.56277778e+00]
 [4.56277778e+00 2.18055556e-01]] [5.73571866e+02 1.81744746e-01] [9.99683236e-01 3.16764448e-04] [0.99996834 0.0079578 ]

[[1.         0.40800508]
 [0.40800508 1.        ]] [1.40800508 0.59199492] [0.70400254 0.29599746] [0.70710678 0.70710678]

Molar mass has a variance ~2600× larger than dipole moment, so unstandardised PCA just recovers the mass axis, the standardised result is the one to report.
