In [69]:
import numpy as np

In [70]:
#Q1
reactions = [
    "CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O",
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O",
]
def parse_reaction(rxn):
    f = rxn.split(">")
    if len(f) != 3: raise ValueError("need exactly two '>'")
    return {k: [m for m in x.split(".") if m]
            for k, x in zip(["reactants","reagents","products"], f)}

for r in reactions:
    d = parse_reaction(r)
    print(r); [print(" ", k, len(v), v) for k, v in d.items()]
    print(" ")

print("Reaction 1 is esterification")
print("Empty reagent means no catalyst/solvent was recorded")

CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O
  reactants 2 ['CC(=O)O', 'OCC']
  reagents 2 ['[H+]', '[Cl-]']
  products 2 ['CC(=O)OCC', 'O']
 
C=C.[H][H]>[Pd]>CC
  reactants 2 ['C=C', '[H][H]']
  reagents 1 ['[Pd]']
  products 1 ['CC']
 
c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O
  reactants 2 ['c1ccccc1', 'O=[N+]([O-])O']
  reagents 0 []
  products 2 ['c1ccccc1[N+](=O)[O-]', 'O']
 
Reaction 1 is esterification
Empty reagent means no catalyst/solvent was recorded


In [71]:
#Q2
E=np.array([[2,0,-1,0],[6,0,0,-2],[0,2,-2,-1]])

# perform svd
U, s, Vh = np.linalg.svd(E)

# EXTRACT NULL VECTOR
null_vector = Vh[-1, :]
print("Null Vector:", null_vector)

# RESCALE
norm = np.linalg.norm(null_vector)
null_vector_normalized = null_vector / norm
scaled_null_vector = null_vector_normalized * 2
print("Scaled Null Vector:", scaled_null_vector)

# VERIFY E@x=0
verification_result = E @ scaled_null_vector
print("experimental answer:", verification_result)
print("is it close", np.allclose(verification_result, 0))

Null Vector: [0.19518001 0.68313005 0.39036003 0.58554004]
Scaled Null Vector: [0.39036003 1.3662601  0.78072006 1.17108009]
experimental answer: [-1.11022302e-16 -4.44089210e-16 -2.22044605e-16]
is it close True


In [72]:
#Q3
import numpy as np

A = np.zeros((4,4))

for i in range(3):
  A[i, (i + 1) ] = 1
  A[(i + 1) , i] = 1

eigenvalues = np.linalg.eigvalsh(A)
eigenvalues.sort()
eigenvalues = eigenvalues[::-1]

E_pi = 2 * eigenvalues[0] + 2 * eigenvalues[1]

delocal_energy_coeff = E_pi - 4

print("Adjacency Matrix (A):\n", A)
print("\nEigenvalues (descending):", eigenvalues)
print(f"\nE_pi: 4*alpha + {E_pi:}*beta")
print(f"Delocalisation Energy: {delocal_energy_coeff:}*beta")

Adjacency Matrix (A):
 [[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]

Eigenvalues (descending): [ 1.61803399  0.61803399 -0.61803399 -1.61803399]

E_pi: 4*alpha + 4.47213595499958*beta
Delocalisation Energy: 0.4721359549995796*beta


In [73]:
#Q4
import numpy as np

A=np.zeros((6, 6))
for i in range(6):
    A[i, (i + 1) % 6] = A[(i + 1) % 6, i] = 1.0

At=A+np.eye(6)
P=At/At.sum(axis=1,keepdims=True)

H=np.random.default_rng(1).normal(size=(6, 3))

v=np.linalg.eigvals(P)
v=np.sort(np.abs(v))[::-1]
mu= v[1]

print("eigenvalue moduli:", v)
print("mu:", mu)

for k in [0, 1, 2, 4, 8, 16]:
    Z = H.copy()
    for _ in range(k):
        Z = P @ Z
    d = np.max(np.linalg.norm(Z - Z.mean(axis=0), axis=1))
    print(k, d)

eigenvalue moduli: [1.00000000e+00 6.66666667e-01 6.66666667e-01 3.33333333e-01
 7.91848035e-17 3.92523115e-17]
mu: 0.6666666666666667
0 1.2413880520727198
1 0.5368253372377662
2 0.3459101833698203
4 0.1548726398897235
8 0.030667573455258054
16 0.0011967999497354295


In [74]:
#Q5
import numpy as np

X = np.array([[78.1, 2.3],
              [92.1, 1.7],
              [106.2, 2.8],
              [120.2, 0.7],
              [134.2, 3.1],
              [148.2, 2.4]])

def pca(X):
    Xc = X - X.mean(axis=0)
    C = Xc.T @ Xc / len(X)
    w, v = np.linalg.eigh(C)
    j = np.argsort(w)[::-1]
    w, v = w[j], v[:, j]
    for i in range(v.shape[1]):
        q = np.argmax(np.abs(v[:, i]))
        if v[q, i] < 0:
            v[:, i] *= -1
    return C, w, w / w.sum(), v

C, w, f, v = pca(X)
Z = (X - X.mean(axis=0)) / X.std(axis=0)
Cz, wz, fz, vz = pca(Z)

print("centered covariance:\n", C)
print("eigenvalues:", w)
print("fraction:", f)
print("PC1:", v[:, 0])

print("\nstandardized covariance:\n", Cz)
print("eigenvalues:", wz)
print("fraction:", fz)
print("PC1:", vz[:, 0])

centered covariance:
 [[573.53555556   3.03888889]
 [  3.03888889   0.61888889]]
eigenvalues: [573.55167411   0.60277034]
fraction: [0.99895016 0.00104984]
PC1: [0.99998593 0.00530402]

standardized covariance:
 [[1.         0.16129775]
 [0.16129775 1.        ]]
eigenvalues: [1.16129775 0.83870225]
fraction: [0.58064887 0.41935113]
PC1: [0.70710678 0.70710678]
