##Question 4

In [ ]:
import numpy as np

A6 = np.zeros((6,6))
for i in range(6):
    A6[i,(i+1)%6] = A6[(i+1)%6,i] = 1.0

H = np.random.default_rng(1).normal(size=(6,3))

A_tilde = A6 + np.eye(6)

P = A_tilde / A_tilde.sum(axis=1, keepdims=True)

eigvals = np.linalg.eigvalsh(P)
eigvals_sorted = np.sort(np.abs(eigvals))[::-1]
mu = eigvals_sorted[1]

print("A_tilde:\n", A_tilde)
print("P:\n", P)
print("eigenvalues of P:", eigvals_sorted)
print("mu (smoothing rate, SLEM):", mu)
print()

ks = [0, 1, 2, 4, 8, 16]
for k in ks:
    Pk = np.linalg.matrix_power(P, k)
    Hk = Pk @ H
    mean_row = Hk.mean(axis=0, keepdims=True)
    deviation = Hk - mean_row
    max_dev = np.max(np.abs(deviation))
    print(f"k={k:2d}: max deviation from mean row = {max_dev:.6f}")

A_tilde:
 [[1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1.]]
P:
 [[0.33333333 0.33333333 0.         0.         0.         0.33333333]
 [0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.33333333 0.         0.        ]
 [0.         0.         0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333]
 [0.33333333 0.         0.         0.         0.33333333 0.33333333]]
eigenvalues of P: [1.00000000e+00 6.66666667e-01 6.66666667e-01 3.33333333e-01
 9.62763812e-17 3.13258287e-17]
mu (smoothing rate, SLEM): 0.6666666666666667

k= 0: max deviation from mean row = 1.080157
k= 1: max deviation from mean row = 0.400476
k= 2: max deviation from mean row = 0.252188
k= 4: max deviation from mean row = 0.113728
k= 8: max deviation from mean row = 0.022566
k=16: max deviation from mean row = 0.000881


##Question 3

In [ ]:
import numpy as np

A = np.zeros((4, 4))
for i in range(3):
    A[i, i+1] = 1
    A[i+1, i] = 1

eigvals = np.linalg.eigvalsh(A)
eigvals_sorted = np.sort(eigvals)[::-1]

n_pi_electrons = 4
n_occupied = n_pi_electrons // 2

E_pi = 2 * np.sum(eigvals_sorted[:n_occupied])

n_double_bonds = n_pi_electrons // 2
E_localized = 2 * n_double_bonds * 1

delocalization_energy = E_pi - E_localized

degrees = A.sum(axis=1)
for i, d in enumerate(degrees):
    print(f"Atom {i}: degree = {int(d)}")

print("Eigenvalues (descending):", eigvals_sorted)
print("E_pi (units of beta):", E_pi)
print("Delocalization energy (units of beta):", delocalization_energy)
print(f"Delocalization energy in terms of benzene(2)beta: {delocalization_energy/2:.4f} x 2beta")

Atom 0: degree = 1
Atom 1: degree = 2
Atom 2: degree = 2
Atom 3: degree = 1
Eigenvalues (descending): [ 1.61803399  0.61803399 -0.61803399 -1.61803399]
E_pi (units of beta): 4.47213595499958
Delocalization energy (units of beta): 0.4721359549995796
Delocalization energy in terms of benzene(2)beta: 0.2361 x 2beta


##Question 5

In [ ]:
import numpy as np

X = np.array([[78.1, 2.3],
              [92.2, 1.7],
              [106.2, 2.8],
              [120.2, 2.0],
              [134.2, 3.1],
              [148.2, 2.4]])

X_centered = X - X.mean(axis=0)
cov_centered = np.cov(X_centered, rowvar=False)
eigvals_c, eigvecs_c = np.linalg.eigh(cov_centered)
order_c = np.argsort(eigvals_c)[::-1]
eigvals_c = eigvals_c[order_c]
eigvecs_c = eigvecs_c[:, order_c]
explained_var_ratio_c = eigvals_c / eigvals_c.sum()

X_std = (X - X.mean(axis=0)) / X.std(axis=0, ddof=1)
cov_std = np.cov(X_std, rowvar=False)
eigvals_s, eigvecs_s = np.linalg.eigh(cov_std)
order_s = np.argsort(eigvals_s)[::-1]
eigvals_s = eigvals_s[order_s]
eigvecs_s = eigvecs_s[:, order_s]
explained_var_ratio_s = eigvals_s / eigvals_s.sum()

print("Centered PCA")
print("Eigenvalues:", eigvals_c)
print("Principal axes (columns):\n", eigvecs_c)
print("Explained variance ratio:", explained_var_ratio_c)

print("\nStandardized PCA")
print("Eigenvalues:", eigvals_s)
print("Principal axes (columns):\n", eigvecs_s)
print("Explained variance ratio:", explained_var_ratio_s)

print("\nThe two disagree because centered PCA's variance is dominated by molar mass's larger raw scale (~78-148 vs ~1.7-3.1), "
      "not by any real chemical relationship — standardized PCA is the one to report, since it puts both features on equal footing.")

Centered PCA
Eigenvalues: [6.87445075e+02 2.18257873e-01]
Principal axes (columns):
 [[-0.99996842  0.00794765]
 [-0.00794765 -0.99996842]]
Explained variance ratio: [9.99682609e-01 3.17390593e-04]

Standardized PCA
Eigenvalues: [1.40723557 0.59276443]
Principal axes (columns):
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
Explained variance ratio: [0.70361778 0.29638222]

The two disagree because centered PCA's variance is dominated by molar mass's larger raw scale (~78-148 vs ~1.7-3.1), not by any real chemical relationship — standardized PCA is the one to report, since it puts both features on equal footing.


##Question 1

In [ ]:

reactions = [
    "CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O",
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O",
]


def parse_reaction(rxn):
    fields = rxn.split(">")

    if len(fields) != 3:
        raise ValueError("Reaction must contain exactly three fields")

    fields = [
        [item for item in field.split(".") if item]
        for field in fields
    ]

    return fields

for rxn in reactions:
    print("Reaction:", rxn)

    reactants, reagents, products = parse_reaction(rxn)

    print("Reactants:", reactants)
    print("Reagents :", reagents)
    print("Products :", products)
    print()
    print("Esterification: Reaction 1; the empty reagent field in Reaction 3 means no reagent or reaction condition is specified.")

Reaction: CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O
Reactants: ['CC(=O)O', 'OCC']
Reagents : ['[H+]', '[Cl-]']
Products : ['CC(=O)OCC', 'O']

Esterification: Reaction 1; the empty reagent field in Reaction 3 means no reagent or reaction condition is specified.
Reaction: C=C.[H][H]>[Pd]>CC
Reactants: ['C=C', '[H][H]']
Reagents : ['[Pd]']
Products : ['CC']

Esterification: Reaction 1; the empty reagent field in Reaction 3 means no reagent or reaction condition is specified.
Reaction: c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O
Reactants: ['c1ccccc1', 'O=[N+]([O-])O']
Reagents : []
Products : ['c1ccccc1[N+](=O)[O-]', 'O']

Esterification: Reaction 1; the empty reagent field in Reaction 3 means no reagent or reaction condition is specified.


##Question 2

In [17]:

import numpy as np


E = np.array([
    [2., 0., -1.,  0.],
    [6., 0.,  0., -2.],
    [0., 2., -2., -2.]
])

U, S, Vh = np.linalg.svd(E)


print("Singular values:")
print(S)

rank = np.linalg.matrix_rank(E)
print("\nRank:", rank)


nullity = E.shape[1] - rank
print("Nullity:", nullity)


x = Vh[-1, :]

print("\nNull vector from SVD:")
print(x)


x_scaled = x / x[0]

print("\nCoefficients scaled to C2H6 = 1:")
print(x_scaled)


x_integer = x_scaled / np.min(np.abs(x_scaled[np.abs(x_scaled) > 1e-10]))


x_integer = np.round(x_integer).astype(int)

print("\nSmallest whole-number coefficients:")
print(x_integer)


product = E @ x_integer

print("\nE @ x:")
print(product)

print("\nVerification:")
print(np.allclose(product, 0))

Singular values:
[6.65746079 3.38355664 1.10894556]

Rank: 3
Nullity: 1

Null vector from SVD:
[0.16012815 0.80064077 0.32025631 0.48038446]

Coefficients scaled to C2H6 = 1:
[1. 5. 2. 3.]

Smallest whole-number coefficients:
[1 5 2 3]

E @ x:
[0. 0. 0.]

Verification:
True
