In [1]:
import numpy as np

**Question 01**

In [2]:
# given
reactions = [
    "CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O",
    "C=C.[H][H]>[Pd]>CC",
    "c1ccccc1.O=[N+]([O-])O>>c1ccccc1[N+](=O)[O-].O"
]

In [9]:
# defining function parse_reaction(rxn) that returns a dictionary with keys reactants, reagents, products
def parse_reaction(rxn):
  # split on ">", check there are three fields, return value error if exactly two > are not present
  fields = rxn.split(">")
  if len(fields) != 3:
    raise ValueError("Reaction must have exactly three fields separated by '>'")
  # split each field on "." and drop empty entries
  reactants = [r.strip() for r in fields[0].split(".") if r.strip()]
  reagents = [r.strip() for r in fields[1].split(".") if r.strip()]
  products = [r.strip() for r in fields[2].split(".") if r.strip()]
  # for every string, print each field with number of molecules it contains and the list itself
  print(f"Reactants: {len(reactants)} molecules")
  print(reactants)
  print(f"Reagents: {len(reagents)} molecules")
  print(reagents)
  print(f"Products: {len(products)} molecules")
  print(products)
  pass

In [10]:
for r in reactions:
  parse_reaction(r)

Reactants: 2 molecules
['CC(=O)O', 'OCC']
Reagents: 2 molecules
['[H+]', '[Cl-]']
Products: 2 molecules
['CC(=O)OCC', 'O']
Reactants: 2 molecules
['C=C', '[H][H]']
Reagents: 1 molecules
['[Pd]']
Products: 1 molecules
['CC']
Reactants: 2 molecules
['c1ccccc1', 'O=[N+]([O-])O']
Reagents: 0 molecules
[]
Products: 2 molecules
['c1ccccc1[N+](=O)[O-]', 'O']




1.   Reaction 1, i.e., "CC(=O)O.OCC>[H+].[Cl-]>CC(=O)OCC.O" is an esterification reaction.
2.   The empty reagent field implies that the reactants do not require a catalyst/medium to react.



**Question 02**

In [6]:
# columns: C2H6, O2, CO2, H2O and rows: C, H, O
E = np.array([[2., 0., -1., 0.,],
              [6., 0., 0., -2.,],
              [0., 2., -2., -1.]])

In [45]:
# SVD
S = np.linalg.svd(E, compute_uv=False)
# extract the null vector
v = np.linalg.svd(E)[2][-1]
# coefficients rescaled to C2H6 = 1
x = v/v[0]; xv = x*2
# print singular values
print(S)
# rank and nullity of E
print(f"Rank: {np.linalg.matrix_rank(E)}")
print(f"Nullity: {len(S) - np.linalg.matrix_rank(E)}")
# print rescaled coefficients
print(f"C2H6 = {xv[0]}, O2 = {xv[1]}, CO2 = {xv[2]}, H2O = {xv[3]}")
# print smallest whole number coefficients
print(f"C2H6 = {int(xv[0])}, O2 = {int(xv[1])}, CO2 = {int(xv[2])}, H2O = {int(xv[3])}")
# print E @ x = 0
print(f"E @ x = {np.dot(E, x)}")

[6.62561256 3.00720721 1.02857332]
Rank: 3
Nullity: 0
C2H6 = 2.0, O2 = 7.000000000000001, CO2 = 4.000000000000001, H2O = 6.000000000000002
C2H6 = 2, O2 = 7, CO2 = 4, H2O = 6
E @ x = [-4.44089210e-16 -1.77635684e-15 -8.88178420e-16]


Null space has dimension one implies that

**Question 03**

In [31]:
A = np.zeros((4, 4))

# bond atom i to atom i+1 for i = 0, 1, 2 like a chain, not ring
for i in range(3):
  A[i, i+1] = A[i+1, i] = 1.0
# print eigenvalues sorted descending
w = np.sort(np.linalg.eigvals(A))[::-1]
print(v)
# print E_pi in 4*alpha + n*beta form
print(f"E_pi = {2*v[0]}*alpha + {2*v[1]}*beta")
# print delocalization energy which is E_pi - 4*alpha - 4*beta
print(f"Delocalization energy = {2*v[1] - 4}")

[ 1.61803399  0.61803399 -0.61803399 -1.61803399]
E_pi = 3.2360679774997885*alpha + 1.2360679774997894*beta
Delocalization energy = -2.7639320225002106


The delocalization energy of benzene tells us that the molecule has more delocalized electrons and is thus more stable.

**Question 04**

In [16]:
A6 = np.zeros((6, 6))
for i in range(6):
  A6[i, (i+1)%6] = A6[(i+1)%6, i] = 1.0
H = np.random.default_rng(1).normal(size=(6,3))

In [20]:
A_tidle = A6 + np.eye(6)
print(A_tidle)

[[1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1.]]


In [21]:
D_tidle_diag = np.sum(A_tidle, axis=1)
D_tidle = np.diag(D_tidle_diag)
P = np.linalg.inv(D_tidle) @ A_tidle
print(P)

[[0.33333333 0.33333333 0.         0.         0.         0.33333333]
 [0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.33333333 0.         0.        ]
 [0.         0.         0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333]
 [0.33333333 0.         0.         0.         0.33333333 0.33333333]]


In [47]:
# smoothening rate mu
EP = np.sort(abs(np.linalg.eigvals(P)))[::-1]
# print the second largest eigenvalue modulus of P
print(EP[1])

0.6666666666666667


In [52]:
# the largest deviation of any atom from the mean row at each value of k = 0, 1, 2, 4, 8, 16
for k in [0,1,2,4,8,16]:
    Hk = np.linalg.matrix_power(P,k)@H
    print(k, np.linalg.norm(Hk-Hk.mean(0), axis=1).max())

0 1.2413880520727198
1 0.5368253372377662
2 0.3459101833698204
4 0.15487263988972352
8 0.03066757345525804
16 0.0011967999497353888


As the number of layers increases, the deviation reduces, approaching zero, indicating that all the atoms are close to the mean row.

**Question 05**

In [48]:
X = np.array([
    [78.1, 2.3],
    [92.1, 1.7],
    [106.2, 2.8],
    [120.2, 2.0],
    [134.2, 3.1],
    [148.2, 2.4]
])

In [50]:
# PCA
def pca(M):
    C = M.T@M/len(M); w,V = np.linalg.eigh(C)
    i = np.argsort(w)[::-1]; w,V = w[i], V[:,i]
    V *= np.sign(V[abs(V).argmax(0), [0,1]])
    print(C, w, w/w.sum(), V[:,0])

In [51]:
Xc = X - X.mean(0)
pca(Xc)
print()
pca(Xc/Xc.std(0))
print()

[[5.73535556e+02 4.56277778e+00]
 [4.56277778e+00 2.18055556e-01]] [5.73571866e+02 1.81744746e-01] [9.99683236e-01 3.16764448e-04] [0.99996834 0.0079578 ]

[[1.         0.40800508]
 [0.40800508 1.        ]] [1.40800508 0.59199492] [0.70400254 0.29599746] [0.70710678 0.70710678]



The two analyses disagree